### ISSUE TITLE
setup dev env

### ISSUE THREAD

**Issue by michaelchin** [ModelAtlasofTheEarth/website#1]
@lauren-ilano @cpalfonso

Let's try to setup the dev env. See the link below for instructions

https://github.com/ModelAtlasofTheEarth/website#setup-dev-env

If you find any problem with the instructions, please update the readme for future reference.

**Comment by michaelchin** [comment]
Hi @laurilano @cpalfonso ,

Please comment this issue if you have done the setup successfully and I will close it.

Let me know if you run into any problem.

**Comment by cpalfonso** [comment]
@michaelchin no worries, everything worked just fine for me.

**Comment by laurilano** [comment]
Hi @michaelchin, I followed the steps and am able to see the website with the local host link.

**Comment by michaelchin** [comment]
GOOD!
