### ISSUE TITLE
setup test/staging site with gatsby cloud

### ISSUE THREAD

**Issue by michaelchin** [ModelAtlasofTheEarth/website#2]
See the link below

https://www.gatsbyjs.com/docs/tutorial/getting-started/part-1/#build-your-site-with-gatsby-cloud

this staging site is mainly for the purpose of testing and demonstration

**Comment by michaelchin** [comment]
@laurilano  @cpalfonso 

Any volunteer for this? The main purpose is to connect this repository to gatsby Cloud for a staging server.

**Comment by michaelchin** [comment]
@cpalfonso could you please look into this? thanks

**Comment by cpalfonso** [comment]
@michaelchin all done, it's currently up and running at [https://websitemain60061.gatsbyjs.io](https://websitemain60061.gatsbyjs.io/).
