### ISSUE TITLE
Issue with mp4

### ISSUE THREAD

**Issue by dansand** [ModelAtlasofTheEarth/website#25]
I added a new mp4 for the `sandiford-2021-detachment` model, but it doesn't show up. I converted it to a gif, and it does. need ti investigate problem here.

**Comment by cpalfonso** [comment]
I tried it myself and ran into the same problem, so I did a little digging and it looks like Firefox apparently doesn't support the YUV444 format – however, it works fine for me in Edge. If I convert the video to YUV420, it now works in Firefox as well. I've attached the converted video below, which should hopefully play in your browser:

https://github.com/ModelAtlasofTheEarth/website/assets/60722740/ce73d573-1692-4d26-97c9-9ed4f238d109
