### ISSUE TITLE
list models in a new web page

### ISSUE THREAD

**Issue by michaelchin** [ModelAtlasofTheEarth/website#6]
List models in this page. 

See the notes here https://github.com/ModelAtlasofTheEarth/website#list-markdown-files

- create a new page at http://localhost:8000/models/
- get the model markdown files from @saraemp @dansand 
- list the models in the new web page

@cpalfonso Could you please look into this? Thanks.

**Comment by michaelchin** [comment]
@saraemp @dansand We need some sample markdown files for this page.

**Comment by michaelchin** [comment]
@cpalfonso Could you please use the markdown files in the links below to create this "model list" page? Thanks.

@dansand @saraemp 

https://github.com/ModelAtlasofTheEarth/corcho-2022-collision/tree/main/web_files
https://github.com/ModelAtlasofTheEarth/sandiford-2021-detachment/tree/main/web_files

**Comment by cpalfonso** [comment]
@michaelchin I've set up a list of available models, along with a starting point for the model pages: #9. The build is live here: [https://build-ae2bf927-dccd-4b7e-a302-cdd28eb0af6c.gatsbyjs.io/](https://build-ae2bf927-dccd-4b7e-a302-cdd28eb0af6c.gatsbyjs.io/).
The "Models" button in the navbar takes you to the list of all models, while the tags and authors on each model page link to the list of models matching that author or tag.

**Comment by michaelchin** [comment]
> @michaelchin I've set up a list of available models, along with a starting point for the model pages: #9. The build is live here: https://build-ae2bf927-dccd-4b7e-a302-cdd28eb0af6c.gatsbyjs.io/. The "Models" button in the navbar takes you to the list of all models, while the tags and authors on each model page link to the list of models matching that author or tag.

This looks very nice. Thanks.
